export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER UPDATED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_QUESTIONS_REQUEST = "CREATE_QUESTION_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const SUBMIT_SUBMISSION_REQUEST = "SUBMIT_SUBMISSION_REQUEST";
export const SUBMIT_SUBMISSION_SUCCESS = "SUBMIT_SUBMISSION_SUCCESS";
export const SUBMIT_SUBMISSION_FAILURE = "SUBMIT_SUBMISSION_FAILURE";
